openapi: 3.0.1
info:
  title: '@jupiterone/graph-trend-micro'
  description: A graph conversion tool for https://trendmicro.com
  x-cortex-git:
    github:
      repository: JupiterOne/graph-trend-micro
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-trend-micro'
  x-cortex-service-groups:
    - tier-4
